services:
  mysql:
    image: mysql:8.0
    container_name: task-manager-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=task_manager_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - task-manager-network

  app:
    build: .
    container_name: task-manager-app
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/task_manager_db?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_WEB_CORS_ALLOWED-ORIGINS=http://localhost:4200,http://127.0.0.1:4200,http://localhost:80,http://localhost
      - SPRING_WEB_CORS_ALLOWED-METHODS=GET,POST,PUT,DELETE,OPTIONS
      - SPRING_WEB_CORS_ALLOW-CREDENTIALS=true
      - SPRING_WEB_CORS_ALLOWED-HEADERS=*
      - APP_ADMIN_USERNAME=admin
      - APP_ADMIN_PASSWORD=securePassword123
    networks:
      - task-manager-network

networks:
  task-manager-network:
    driver: bridge

volumes:
  mysql-data: