services:
  mysql:
    image: mysql:8.0
    container_name: task-manager-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=task_manager_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - task-manager-network

  app:
    build: .
    container_name: task-manager-app
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/task_manager_db?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=false
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
      - SPRING_OUTPUT_ANSI_ENABLED=always

      - SPRING_WEB_CORS_ALLOWED_ORIGINS=http://localhost:4200,http://127.0.0.1:4200,http://localhost:80,http://localhost
      - SPRING_WEB_CORS_ALLOWED_METHODS=GET,POST,PUT,DELETE,OPTIONS
      - SPRING_WEB_CORS_ALLOW_CREDENTIALS=true

      - JWT_SECRET=taskmanagerapplication2025buidbynipunsathsara@20250405
      - JWT_EXPIRATION=86400000

      - APP_ADMIN_USERNAME=admin
      - APP_ADMIN_PASSWORD=admin123
    networks:
      - task-manager-network

networks:
  task-manager-network:
    driver: bridge

volumes:
  mysql-data:
