server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/task_manager_db
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  output:
    ansi:
      enabled: always

  web:
    cors:
      allowed-origins: http://localhost:4200
      allowed-methods: GET,POST,PUT,DELETE
      allow-credentials: true

jwt:
  secret: taskmanagerapplication2025buidbynipunsathsara@20250405
  expiration: 86400000

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true